jrl-umi3218/mc_rtc

- binding/python/CMakeLists.txt
- src/mc_control/mc_global_controller.cpp
This PR makes sure mc_rtc doesn't crash right away if a global plugin fails to load
Closes https://github.com/jrl-umi3218/mc_openrtm/issues/2
> Graceful global plugin crashes

- include/mc_tasks/CoMTask.h
- src/mc_tasks/CoMTask.cpp
Fixes #14: Fixes a bug in logging/gui of the com position when using `dimWeight`.
Requires the corresponding PR in `Tasks`: https://github.com/jrl-umi3218/Tasks/pull/64
Note that this MR has an important implications for existing logs:
- The logged `CoM` position from the task (e.g `com_<RobotName>_pos`) is wrong along the dimensions where `dimWeight != 1`.
> [CoMTask] Fix computation of logged CoM position with dimWeight

- binding/python/mc_control/fsm/c_fsm.pxd
- binding/python/mc_control/fsm/fsm.pyx
- doc/_data/schemas/common/fsm_contact.json
- doc/_data/schemas/mc_rbdyn/Contact.json
- doc/_examples/json/mc_rbdyn/Contact.json
- doc/_examples/yaml/mc_rbdyn/Contact.yaml
- include/mc_control/fsm/Controller.h
- src/mc_control/fsm/Controller.cpp
- src/mc_control/fsm/states/Parallel.cpp
- src/mc_control/samples/FSM/etc/FSM.conf.cmake
- src/mc_rbdyn/Contact.cpp
- src/mc_rbdyn/configuration_io.cpp
- src/mc_solver/QPSolver.cpp
This brings friction setting support for FSM contacts as well
This also fixes small issues with friction support in `mc_rbdyn::Contact` and a bug in removing contact from the GUI
> Add contact friction for FSM contacts

- CHANGELOG.md
- binding/python/mc_control/c_mc_control.pxd
- binding/python/mc_control/mc_control.pyx
- include/mc_control/MCController.h
- include/mc_rtc/ConfigurationHelpers.h
- src/mc_control/MCController.cpp
- src/mc_control/samples/FSM/src/mc_fsm_controller.h
- src/mc_control/samples/LIPMStabilizer/src/mc_lipm_stabilizer.h
- Enforces the list of supported robots defined through MCController::supported_robots() (previously ignored):
- If the list is empty, all robots are considered supported
- If there are robot names in the list, then only these robots are allowed as the main robot, and the controller will throw upon `MCController::reset`.
- Properly silences exceptions in ConfigurationHelpers.
> [MCController] Enforce the list of supported robots

- CHANGELOG.md
- include/mc_tasks/MetaTask.h
- include/mc_tasks/TrajectoryTaskGeneric.h
- include/mc_tasks/TrajectoryTaskGeneric.hpp
- src/mc_tasks/ComplianceTask.cpp
- src/mc_tasks/EndEffectorTask.cpp
- src/mc_tasks/PostureTask.cpp
Ensures that joint names are valid before passing them to tasks' `JointSelector`.
Fixes https://gite.lirmm.fr/multi-contact/mc_rtc/issues/151
> [MetaTasks] Ensures that joints exist for selectActiveJoints*

- .github/workflows/build.yml
- .github/workflows/docker/Dockerfile
- .gitignore
- doc/tutorials/introduction/installation-guide.md
- utils/build_and_install.sh
- utils/build_and_install_default_config.sh
- utils/build_and_install_user_config.sample.sh
This PR proposes the following improvements to the `build_and_install.sh` script:
- Prevent running the script as `root` user by default.
Doing so causes unexpected issues down the line when attempting to use mc_rtc as a normal user. Notably if one tries to use mc_rtc as a normal user after the script succeeds: the GUI silently fails as it cannot recreate the IPC files in `/tmp`, the unit tests fail as the log files cannot be created, etc etc.
Now by default, the script will stop with an error if you attempt to run it as root. Use `ALLOW_ROOT=true` or `--allow-root true` if you still wish to install everything as root (typically CI/Docker).
- Introduces user configuration:
- The default configuration options are defined in `build_and_install_default_config.sh`
- They may be overridden by …
> Improvements to build_and_install (interfaces, user configuration)

- include/mc_rbdyn/BodySensor.h
- include/mc_rbdyn/Device.h
- include/mc_rbdyn/ForceSensor.h
- src/mc_rbdyn/Device.cpp
- src/mc_rbdyn/ForceSensor.cpp
- src/mc_rbdyn/Robot.cpp
This PR simplifies writing new devices extension:
- Allow to create a Device without specifying dummy values for the parent body and transformation, those are filled up when the device is created in the robot
- Make Device non-copiable by default
> Simpler and safer device interface

- include/mc_solver/QPSolver.h
- src/mc_control/MCController.cpp
- src/mc_solver/QPSolver.cpp
This PR keeps track of dynamics constraints that are added to the solver in order to compute output torques automatically after a successful solve
Closes #209 (GitLab)
> [mc_solver] Compute output torques if a DynamicsConstraint is added

- binding/python/mc_rbdyn/c_mc_rbdyn.pxd
- binding/python/mc_rbdyn/mc_rbdyn.pyx
- doc/_data/schemas/mc_rbdyn/Collision.json
- include/mc_rbdyn/Robot.h
- include/mc_rbdyn/RobotModule.h
- include/mc_solver/CollisionsConstraint.h
- src/mc_rbdyn/Robot.cpp
- src/mc_rbdyn/RobotModule.cpp
- src/mc_solver/CollisionsConstraint.cpp
This PR:
- Loads simple collision shapes defined in URDF files `<collision>` tags, for each `<collision>` tag in the URDF it will create a collision object named `body_{i}` where `i` depends of the order in which these collision tags are in the URDF file. When a single collision entry exist then the suffix is dropped. If there is a single collision entry and a convex already exists then the simple collision shape is dropped in favor of the convex
- Supports wildcard when adding collisions, so instead of adding MxN collision (in yaml or code) for `[bodyA_0, bodyA_1, ..., bodyA_M]` and ``[bodyB_0, bodyB_1, ..., bodyB_N]` we can simply specify collision avoidance between `bodyA*` and `bodyB*`
- Use newly added accessors in Tasks to provide visual feedback on collision avoidance (show …
> Simple collisions, wildcard support and collision monitoring

- include/mc_solver/GenericLoader.h
- include/mc_solver/GenericLoader.hpp
This solves ambiguous call in cases such as:
```cpp
auto task = mc_tasks::MetaTaskLoader::load(solver(), "/my/path/task.yaml");
```
which are advertised in the [tutorials](https://jrl-umi3218.github.io/mc_rtc/tutorials/introduction/ef-controller.html)
> [mc_solver] Add C-style string overload for GenericLoader

- include/mc_rtc/Configuration.h
- include/mc_rtc/ConfigurationHelpers.h
- include/mc_rtc/logging.h
- src/mc_rbdyn/configuration_io.cpp
- src/mc_rtc/Configuration.cpp
- tests/testConfiguration.cpp
This PR improves error reporting when an error occurs in a Configuration conversion. Instead of only reporting the failure it will also report the Configuration path that lead to the error.
This is (almost) free when the exception is caught and silenced but relatively expensive (a linear search on every configuration entries) otherwise as we need to look for the faulty value in the whole document. It is completely free when no exception is generated.
Generally this is fine as uncaught exception will lead to the program termination. Unsilenced exceptions are barely used in the framework and normally with small objects. (if I'm not mistaken this only done in the GUI callback handling)
Example outputs:
```
// code: Eigen::Vector3d v = config("v6d");
[error] Stored Json value is not a …
```
> improve configuration error reporting

- doc/_data/schemas/MetaTask/SurfaceTransformTask.json
- doc/_data/schemas/common/completion_wrench.json
- include/mc_tasks/AdmittanceTask.h
- include/mc_tasks/SurfaceTransformTask.h
- src/mc_tasks/AdmittanceTask.cpp
- src/mc_tasks/SurfaceTransformTask.cpp
This PR adds support for `wrench` as a completion criteria in `SurfaceTransformTask`. This makes it easy to do things such as going towards a contact at constant velocity and stopping when a force threshold is reached.
Example:
```yaml
EstablishContactWithConstantVel:
base: MetaTasks
AddContacts:
- r1: hrp4
r2: tilted_board  
r1Surface: RightHandPad
r2Surface: AllGround
dof: [1, 1, 1, 1, 1, 0]
AddContactsAfter:
- r1: hrp4
r2: tilted_board  
r1Surface: RightHandPad
r2Surface: AllGround
dof: [1, 1, 1, 1, 1, 1]
tasks:
RightHandConstantVelocity:
type: surfaceTransform
surface: RightHandPad
refVel: [0,0,0,0,0,-0.05] # go towards target at 5cm per second
stiffness: 1                    # we don't care about position
damping: 300               # damping for velocity control
completion:
wrench: …
```
> [SurfaceTransform] Support for wrench completion criteria

- CHANGELOG.md
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_observers/KinematicInertialPoseObserver.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
This PR adds a simple StabilizerTask constructor that used the configuration stored in the robot module and performs a reasonable default initialization
Also fixes a configuration bug introduced in #61
> Add simplified stabilizer task constructor

- doc/_includes/tutorials/introduction/first-controller/controller.cpp
- doc/_includes/tutorials/introduction/first-controller/controller.h
- doc/_includes/tutorials/introduction/first-controller/controller.py
- doc/_plugins/include_raw.rb
- doc/tutorials/introduction/sources/com-controller.html
- doc/tutorials/introduction/sources/first-controller.html
- doc/tutorials/introduction/sources/multi-robot-controller.html
- Fix inclusion of full source code in tutorials (protects against parsing of liquid tags): Fixes #66 #73 
- Fix source code of first tutorial as suggested in #73
> [doc] Fix tutorial's source code inclusion

- src/mc_rtcMacros.cmake
This PR fixes wrong argument name in add_controller function
> [mc_rtcMacros.cmake] Fix argument name in add_controller when overwriting LIBRARY_OUTPUT_DIRECTORY

- doc/_data/json_categories.yml
- doc/_data/links.yml
- doc/_data/schemas/ConstraintSet/BoundedSpeedConstr.json
- doc/_data/schemas/State/Posture.json
- doc/_data/schemas/common/State.json
- doc/_data/schemas/mc_rbdyn/Collision.json
- doc/_includes/json_schema_category_description.html
- doc/_includes/json_schema_object_property.html
- doc/_includes/schema_categories/ConstraintSet.html
- doc/_includes/schema_categories/MetaTask.html
- doc/_layouts/json.html
- include/mc_control/fsm/Controller.h
- include/mc_control/fsm/State.h
- include/mc_control/fsm/states/MetaTasks.h
- include/mc_tasks/PostureTask.h
- src/mc_control/fsm/Controller.cpp
- src/mc_control/fsm/State.cpp
- src/mc_control/fsm/states/MetaTasks.cpp
- src/mc_rbdyn/configuration_io.cpp
- src/mc_rtc/Configuration.cpp
- src/mc_solver/BoundedSpeedConstr.cpp
- tests/controllers/CMakeLists.txt
- tests/controllers/TestFSMStateOptions.cpp
- tests/controllers/TestFSMStateOptions.in.yaml
- tests/testConfiguration.cpp
- Allow to specify a set of constraints that are added by the state and removed at completion
- Allow to specify a set of tasks that are added by the state and removed at completion
- ^^ `MetaTasks` now uses the capability above and simply load the completion criteria
- RemovePostureTask now removes all active FSM posture tasks or can be specified to remove some of the active posture tasks
Along the way:
- add a test to check that all common state options work correctly
- introduce `oneOf` support for properties in schema doc generation, I will look into supporting this better for some tasks specifications (for now it won't affect the panel)
- fix `mc_rtc::Configuration::empty()` to return false if the configuration holds a non-null value
- fix a long standing bug where loading a nested …
> Improve general states configurability

- utils/build_and_install.sh
- utils/build_and_install_default_config.sh
This is useful in case you want to have a separate build directory for each different CMake option, especially BUILD_TYPE, in order to avoid recompiling everything.
I did not add it as an option for the config sample file but I think the name is self-explanatory and easy to find in the defaults.
I am testing it and it is working. I hope I did not forget a place where it should be.
> Give custom build directories.

- utils/build_and_install.sh
This is a followup to PR #82
It allows one to automatically ignore build directories, so the repos will be clean after the installation.
(Why am I not able to create draft PRs?)
> Ignore the build directory in the corresponding repos

- utils/autocompletion.bash
- utils/autocompletion.zsh
- utils/build_and_install.sh
That requires to source a new file in bashrc / zshrc. 
Tested with zsh and bash.
> Add autocompletion feature to build_and_install script

- include/mc_control/ControllerClient.h
- include/mc_rtc/gui.h
- include/mc_rtc/gui/Robot.h
- include/mc_rtc/gui/elements.h
- src/mc_control/ControllerClient.cpp
- src/mc_control/MCController.cpp
- src/mc_control/mc_global_controller.cpp
- src/mc_rtc/Configuration.cpp
- src/mc_solver/QPSolver.cpp
- tests/dummyServer.cpp
- utils/mc_log_gui/mc_log_ui/mc_log_ui.py
The main goal of this PR is to add a new GUI element: Robot
This allows GUI implementations to display the robot
Also included in this PR, some minor changes:
- [3rd-party] Bump embedded Qhull version
- [mc_rtc] Accept 3D matrix and rpy representation to read Quaternions from a configuration
- [mc_control] Add computed contact forces to the GUI
- [ControllerClient] Fix an issue with trajectory de-serialization
- [ControllerClient] Always read the latest message from the publisher
- [ControllerClient] Make the default widget implementation virtual
- [ControllerClient] Add a synchronous run method
- [tests] Add more elements to the dummy GUI server
> Add Robot to GUI elements

- include/mc_solver/EqualityConstraint.h
- include/mc_solver/GenInequalityConstraint.h
- include/mc_solver/InequalityConstraint.h
This PR adds a note to the `EqualityConstraintForce` documentation about the reference frame in which the contact wrench is expressed (contact surface frame of the first robot `r1Index` involved in the contact).
> [doc] Indicate the contact wrench ref. frame in EqualityConstraintForce

- include/mc_tasks/lipm_stabilizer/Contact.h
- src/mc_tasks/lipm_stabilizer/Contact.cpp
`lipm_stabilizer::Contact::[x|y][min|max]` methods have bug. They returns incorrect value when foot rotates around vertical axis.
These values are used only for visualization (plot and log) and do not affect the robot behavior.
Send the same footstep with/without this pull request. See the max position of support in the last step. It is incorrect before PR (ZMP goes outside of incorrect support range) and becomes correct after PR.
> [lipm_stabilizer::Contact] fix bug in [x|y]min, [x|y]max

- include/mc_rtc/constants.h
Fixed only incorrect comments and variable names. The behavior of the program is originally correct and does not change.
> [mc_rtc/constants.h] fix comments of rad/deg functions

- include/mc_tasks/ImpedanceGains.h
Eigen's cwise operation seems simpler and better than using clamp with imposing a dummy upper limit. https://stackoverflow.com/a/38486309
This Pull Request should not change the behavior of the program.
> [ImpedanceGain] use Eigen cwise operation for applying lower limit

- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_rbdyn/lipm_stabilizer/ZMPCCConfiguration.h
The intent of this PR is to allow to consistently incrementally change the `StabilizerConfiguration` parameters when calling `StabilizerConfiguration::load(mc_rtc::Configuration)` multiple times.
```cpp
auto conf = stabilizer->config();
// Default value for conf.dcmBias.dcmMeasureErrorStd = 0.01
conf.dcmBias.dcmMeasureErrorStd = 5;
mc_rtc::Configuration newConf;
newConf.add("dcm_bias");
newConf("dcm_bias").add("biasDriftPerSecondStd", 0.0001);
conf.load(newConf);
stabilizer->configure(conf);
// Now conf.dcmBias.dcmMeasureErrorStd = 0.01, aka the default value instead of the value '5' we've set previous
// conf.dcmBias.dcmMeasureErrorStd = 0.0001 as expected
```
That is nested types (`DCMBiasEstimatorConfiguration`, `ZMPCCConfiguration`, etc) are first reset to their default configuration …
> [stabilizer] Consistently load the configuration

- doc/_data/schemas/Observers/ObserverPipeline.json
- doc/tutorials/recipes/observers.md
- include/mc_observers/ObserverPipeline.h
- src/mc_observers/ObserverPipeline.cpp
- utils/config_build_and_install.macos.sh
This PR adds to new options to `ObserverPipeline`:
- `required: false`: load an observer if it exists on the system/is loadable, ignore it otherwise.
One example use case for that is `LIPMWalking` controller currently: when the `AttitudeObserver` exists, it is better to use it, but one might want to use only the integrated `KalmanFilter` (@mmurooka didn't have it on his system because it's an external dependency for now for example so he commented it out for now).
- `successRequired: false`: allow a specific observer to fail without affecting the status of the pipeline
Concrete example:
```yaml
ObserverPipelines:
name: "LIPMWalkingObserverPipeline"
gui: true
observers:
- type: Encoder
- type: Attitude
required: false # If the attitude observer is not present, the kalman filter updates the …
```
> [observers] Add options to make observers optional/allowed to fail

- utils/mc_log_gui/mc_log_ui/mc_log_plotcanvas.py
- utils/mc_log_gui/mc_log_ui/mc_log_tab.py
- utils/mc_log_gui/mc_log_ui/mc_log_types.py
- utils/mc_log_gui/mc_log_ui/mc_log_ui.py
- utils/mc_log_gui/mc_log_ui/mc_log_utils.py
This PR fixes multiple issues with `mc_log_ui` and in particular the animated plots:
**Allow to generate animated plots with missing data.**
Previously, trying to plot an animation with non-continous data (e.g. repeatedly adding/removing a task) would crash. Looking at the original PR (https://github.com/jrl-umi3218/mc_rtc/pull/13), it seems that the intent was to first generate a time range corresponding to valid data, and then generating a live plot for this time range. This is however not very intuitive, and still not crash-proof in case there are multiple curves displayed.
The new implementation:
- Looks for the first/last non-nan data amongst all displayed curves to automatically find the suitable time-range for the animation
- Fixes the computation of plot limits, notably for XY …
> [mc_log_ui] Fix various issues (animations, saving, plot limits, default style, etc)

- doc/tutorials/samples/list-of-samples.md
- include/mc_rtc/gui/StateBuilder.h
- include/mc_rtc/log/Logger.h
- include/mc_tasks/SplineTrajectoryTask.hpp
- tests/testSchemaExamples.in.cpp
Without explicitly specifying `this->` like this PR, you get the following SEGV when running the [admittance sample](https://jrl-umi3218.github.io/mc_rtc/tutorials/samples/sample-admittance.html). Also, you get SEGV when stepping forward/backward with `LIPMStabilizer` controller probably for the same reason.
It didn't happen before, so it may start to happen after [the latest logger update](https://github.com/jrl-umi3218/mc_rtc/pull/115). But I don't know the actual reason why this change is needed.
I haven't checked if there is any other place (i.e., template task class) that needs similar fix.
```
Thread 25 "choreonoid" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff61504700 (LWP 3003)]
mc_rbdyn::Robots::robot (this=0xbf202026160d2447, idx=1274965924) at …
```
> Spline trajectory task log fix

- src/mc_control/samples/Admittance/src/mc_admittance_sample_controller.cpp
The gravity force of the right hand is pointing upwards. This is because the force value and visualization frame mismatch.
The gravity force of the right hand is correctly pointing downwards.
As another effect of this PR, the force value reflecting calibration will be visualized. (But the calibration has not been performed yet for JVRC1 in the environment where this screenshot is captured.)
> [mc_control/samples/Admittance] Fix force visualization frame

- .github/workflows/build.yml
- include/mc_rtc/DataStore.h
This PR changes the way type-checking is done in the `DataStore`
The issue is similar to what is described [here](https://stackoverflow.com/questions/19496643/using-clang-fvisibility-hidden-and-typeinfo-and-type-erasure) where the combination of `-fvisibility=hidden`  (which we use in mc_rtc) and `libc++` means the same non-visible types get different `typeid`.
Thus the `DataStore` now does type-checking in two ways:
- first the type's id is compared with known viable ids (current behaviour)
- if that fails, it will compare the demangled type names
In the good scenario (no type issue and all types are visible) this has no extra cost compared to the current implementation. It fixes the non-ideal scenario where all types are not visible for libc++ with a small overhead to check the type …
> Fix DataStore issue with libc++

- include/mc_tasks/ImpedanceTask.h
- src/mc_tasks/ImpedanceTask.cpp
This PR add function to hold the target pose in impedance task.
In hold mode, the compliance modification (deltaCompPoseW_) is automatically updated so that the final target pose sent to the QP (i.e. compliancePose()) remains constant even if the user-specified target pose changes. This is useful when the user wants to change the target pose without moving the object held by the robot (e.g., when there is an error in the object pose and it is corrected based on vision sensor measurements).
Below are the results of a brief test of a simple controller. [Impedance Controller](https://github.com/mmurooka/mc_rtc/tree/impedance-hold-sample/src/mc_control/samples/Impedance) in [mmurooka/impedance-hold-sample branch](https://github.com/mmurooka/mc_rtc/tree/impedance-hold-sample) is used.
In this …
> [mc_tasks] add hold function of impedance task

- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
The stabilizer is not disabled correctly even when you push the button to disable or set yaml configuration to disable.
This is because the `disable()` method updates the configuration to disable the stabilizer
https://github.com/jrl-umi3218/mc_rtc/blob/7889be0eaf8a13e4ba8761121883497b744539a6/src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp#L296-L304
But the updated configuration is overwritten with original one in `update()` method (this is incorrect)
https://github.com/jrl-umi3218/mc_rtc/blob/7889be0eaf8a13e4ba8761121883497b744539a6/src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp#L247-L251
I'm not sure if this is the best implementation, as the configuration is treated in a bit confusing way.
> Fix the stabilizer to be disabled correctly

- src/mc_observers/KinematicInertialPoseObserver.cpp
When the IMU is not directly attached to the base link, the transformation between the IMU orientation and the base link orientation needs to be considered. The former code was applying this transformation
the wrong way around. In most cases this wasn't noticable, as the IMU frame is typically aligned with the base link frame. However, on HRP2,the IMU is located in the chest, whose orientation is arbitrary.
I only tested in simulation so far, but this seems to fix the issue #120.
Below is the curve corresponding to moving forward, turning 90deg in place, then moving forward again. The walk was done with the torso pitched `0.3rad` to further emphasize the problem. Without this patch the robot falls immediately while rotating, while with the patch I didn't notice any difference of behaviour …
> [bugfix][KinematicInertialObserver] Fix orientation transform between IMU and base link

- doc/_data/schemas/mc_rbdyn/RobotModule.json
- doc/_data/schemas/mc_rbdyn/S_ObjectPtr.json
- doc/_examples/json/mc_rbdyn/S_ObjectPtr.json
- doc/_examples/yaml/mc_rbdyn/S_ObjectPtr.yaml
- include/mc_rbdyn/Robot.h
- include/mc_rbdyn/RobotModule.h
- include/mc_rbdyn/configuration_io.h
- src/mc_rbdyn/Robot.cpp
- src/mc_rbdyn/configuration_io.cpp
Closes #162
This PR adds a new field to `RobotModule`, namely `_collisionObjects` (or `rm.collisionObjects()`), which allows to add collision primitives to a robot that can be named.
Example, in a C++ `RobotModule` implementation
```cpp
_collisionObjects["dummy_sphere"] = {"L_WRIST_Y_S", std::make_shared<sch::S_Sphere>(0.1)};  
_collisionObjects["dummy_box"] = {"R_WRIST_Y_S", std::make_shared<sch::S_Box>(0.1, 0.1, 0.1)};
_collisionObjects["dummy_cyl"] = {"R_WRIST_Y_S", std::make_shared<sch::S_Cylinder>(sch::Point3{0, 0, -0.25}, sch::Point3{0, 0, -0.5}, 0.1)}; 
```
And in a YAML module:
```yaml
collisionObjects:
dummy_sphere:
- panda_link7
- type: sphere
radius: 0.1
dummy_box:
- panda_link7
- type: box
width: 0.5
height: 0.5
depth: 0.5
dummy_cylinder:
- panda_link7
- type: cylinder
p1: …
```
> [mc_rbdyn] Allow a RobotModule to specify extra collision objects

- include/mc_control/ControllerClient.h
- include/mc_rtc/gui/Form.h
- src/mc_control/ControllerClient.cpp
This PR adds some information for the `ControlClient` so that it can distinguish wether a default form value was provided by the user or not.
The client should then act as follows when sending a form request:
- Send the default value if it was provided by the user, whether the data is required or not
- Error if the user did not provide a required field and the form has no default value
- Only send the data if the user provided a value when no default value is provided
Relates to #119
I have a PR ready to go for mc_rtc_rviz_panel that improves on form handling there
> Better handle default form values

- doc/_data/tutorials.yml
- doc/_plugins/doxygen.rb.in
- doc/tutorials/advanced/new-plugin.html
- include/mc_control/GlobalPlugin.h
- include/mc_control/mc_global_controller.h
- plugins/ROS/src/plugin/ROS.h
- src/mc_control/mc_global_controller.cpp
A plugin can now provide a configuration object, this object can let mc_rtc know if:
- the plugin implements a before call
- the plugin implements an after call
- the plugin should be called when the global controller is not running
This also adds a documentation page about writing a new plugin for mc_rtc and a new template repository has been introduced [mc-rtc/new-plugin](https://github.com/mc-rtc/new-plugin)
Related to #146
> [GlobalPlugin] Give finer control on plugin calls

- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_tasks/MetaTask.h
- include/mc_tasks/TrajectoryTaskGeneric.hpp
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
This PR is to rename the stabilizer's subtasks correctly when setting the name of StabilizerTask. This PR also contains another commit to save log of weight in TrajectoryTaskGeneric.
It has nothing to do with the contents of the Pull Request, but StabilizerTask outputs a lot of messages on the following lines, which makes it difficult to see other important messages in the loco-manipulation experiments. Is there a good way to easily enable / disable these debug outputs?
https://github.com/jrl-umi3218/mc_rtc/blob/e8081721fe07d1300bcd69b1ab0a36f05b3bacfc/src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp#L222
https://github.com/jrl-umi3218/mc_rtc/blob/e8081721fe07d1300bcd69b1ab0a36f05b3bacfc/src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp#L233
> [mc_tasks] Set name of stabilizer's subtasks

- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
This is necessary for https://gite.lirmm.fr/jrp-2019/mc_hwm_planner/-/merge_requests/14
> [mc_tasks] add getter of comOffsetTarget_ in StabilizerTask

- include/mc_tasks/PostureTask.h
- src/mc_tasks/PostureTask.cpp
- tests/controllers/CMakeLists.txt
- tests/controllers/TestPostureController.cpp
Use `tasks::qp::PostureTask::dimWeight` introduced in https://github.com/jrl-umi3218/Tasks/pull/77
- Improve implementation of selectActiveJoint/selectUnactiveJoints
- Provide accessor/setter
> Implement PostureTask dimWeight

- include/mc_rtc/gui/Form.h
- utils/mc_log_gui/mc_log_ui/mc_log_plotcanvas.py
Fix string value treatment in mc_log_ui. The main fix is to draw the string with the value of the first time step empty correctly.
Follwing bin file is mc_rtc_log generated by Posture controller with https://github.com/jrl-umi3218/mc_rtc/commit/bcb393909b458372384c21075e86cd5fba292fc2 patch.
[mc-log-ui-string-20210731.zip](https://github.com/jrl-umi3218/mc_rtc/files/6911295/mc-log-ui-string-20210731.zip)
With the mc_log_ui without this PR, `Label1` is drawn correctly.
But `Label2` is not drawn correctly (nothing is drawn).
With this PR, it is also drawn correctly.
> [mc_log_ui] Fix string value treatment

- include/mc_rbdyn/Robot.h
- src/mc_rbdyn/Robot.cpp
- src/mc_rbdyn/Robots.cpp
- tests/test_mc_rbdyn.cpp
Previous implementation could fail to copy the robot properly as the
robots_ vector was resized while copying a robot. This commit fixes this
by reforming a valid reference to the copied robot if needed
> [mc_rbdyn] Fix an issue with robot copy

- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
Add `dimWeight` of CoM, torso and pelvis tasks to `StabilizerConfiguration`.
(Especially in my use case, I want to reduce the Z weight of the CoM task.)
> [mc_tasks] add dimWeight of sub tasks to stabilizer configuration

- src/mc_control/fsm/Executor.cpp
When printing a message from `teardown()`, it is easier to understand if it is displayed before the message of starting the next state.
Following is the example of a printing message when switching a state from `HwmStraightObjectMotion` to `HwmUpdateObjectPosePost`.
Before PR:
```
[success] Completed HwmStraightObjectMotion - output: OK
[success] Starting state HwmUpdateObjectPosePost
[info] [HwmStraightObjectMotion] Teardown
```
After PR:
```
[success] Completed HwmStraightObjectMotion - output: OK
[info] [HwmStraightObjectMotion] Teardown
[success] Starting state HwmUpdateObjectPosePost
```
> [mc_control/fsm] print a message of next state starting after teardown of previous state

- src/mc_tasks/PostureTask.cpp
When setting a posture target via a call to the `PostureTask::target` function, the mimic joint targets don't get updated, resulting in an unexpected/undesired robot behavior.
It is done, however, when setting the posture task target in GUI via `NumbeSlider` or `NumberInput`.
This PR adds the mimic joint target update to the `PostureTask::target` function.
> [mc_tasks] Updating mimic joint posture targets

- include/mc_control/fsm/Controller.h
- include/mc_rbdyn/Contact.h
- src/mc_control/samples/CoM/mc_com_controller.cpp
- src/mc_control/samples/FSM/etc/FSM.in.conf
- src/mc_control/samples/FSM/src/mc_fsm_controller.cpp
- src/mc_control/samples/FSM/src/mc_fsm_controller.h
- src/mc_rbdyn/Contact.cpp
- src/mc_rbdyn/configuration_io.cpp
- src/mc_solver/QPSolver.cpp
- tests/controllers/TestCoMTaskController.cpp
The formulation in Tasks is broken when the first robot in a contact has no dof (there is a sign issue)
This PR fixes it by swapping the two robots in that case.
Furthermore, the PR makes the FSM treats contact the same whether they are specified as `r1::s1/r2::s2` or `r2::s2/r1::s1`.
This is not strictly the case at the `mc_solver` level where you can add both contacts (but you can already add the same contact multiple times)
> Fix issues with contacts when the first robot has no dof

- include/mc_control/mc_global_controller.h
- include/mc_observers/EncoderObserver.h
- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_rtc/loader.h
- include/mc_rtc/loader.hpp
- src/mc_control/MCController.cpp
- src/mc_control/fsm/Controller.cpp
- src/mc_control/mc_global_controller.cpp
- src/mc_control/mc_global_controller_configuration.cpp
- src/mc_observers/EncoderObserver.cpp
- src/mc_rtc/loader.in.cpp
The main purpose of this PR is to introduce a multi-robot adapted `init` call for `MCGlobalController` and a `reset` call to restart a controller from a given state without bringing down the whole `MCGlobalController` instance.
This PR also includes three fixes:
- one of the stabilizer configuration entry was not read correctly (this wasn't noticed because this setting is usually left untouched)
- potential segfault on delete when the controller uses the datastore
- protecting calls around `lt_dl*` calls as those are not thread-safe (this would lead to segfault when running many instances of `MCGlobalController` in parallel)
> Add controller reset

- include/mc_control/fsm/Controller.h
- src/mc_control/MCController.cpp
- src/mc_control/fsm/Controller.cpp
- src/mc_rbdyn/Robots.cpp
This PR fixes two issues with robots removal in a controller:
- Remove the robot from GUI and GUI data
- Get rid of the robot name to index map maintained in the FSM controller; this map was not correctly updated and it serves no purpose since the same map is now (correctly) maintained in `mc_rbdyn::Robots`)
> Fix issues with robot removal

- doc/tutorials/tools/mc_log_ui.md
- doc/tutorials/tools/mc_log_utils.md
- include/mc_rtc/log/FlatLog.h
- include/mc_rtc/log/Logger.h
- src/mc_rtc/FlatLog.cpp
- src/mc_rtc/Logger.cpp
- utils/mc_bin_utils.in.cpp
- utils/mc_log_gui/mc_log_ui/mc_log_ui.py
Add --keys option to mc_bin_utils extract
This new option allows to extract a set of keys from a log file
- Automatically adds t
- Only creates a new file when there is a gap in all the keys
New API were added to suppor this:
- FlatLog::getType(k, i) <-- Gets the type at iteration i for the provided  key
- Logger::open opens the provided file (no timestamp, no symlinks)
- Logger::start and Logger::open can start at an arbitrary time
The tool can also be invoked from `mc_log_ui`
ToDo:
> Improve log extract

- src/mc_rtc/internals/yaml.h
- tests/testConfiguration.cpp
That shoud leave only 1/0 and true/false as valid bool representations
Closes #212
> [mc_rtc] Disable yes/no conversion to bool in YAML

- include/mc_control/generic_gripper.h
- src/mc_control/generic_gripper.cpp
- src/mc_control/mc_global_controller_gui.cpp
`mc_control::Gripper` was written with the (unwritten) assumption that the gripper active joints are all revolute. In this PR we detect when this is not the case and improve the behavior when the active joints are prismatic.
- Choose a better reaching threshold for prismatic joints
- Don't do transformations when presenting the safety settings in the GUI
> [mc_control] Better handle "metric" grippers

- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask_log_gui.cpp
This correction allows to correct the position of the CoM in case the DCM bias is coming from a modeling error in the position of the CoM. This has been shown to improve the performance but needs to be limited to avoid winding up in case of contact with the environment.
The option is disabled by default and should not affect existing robots.
> Correct the CoM position to reflect DCM bias

- include/mc_tasks/ImpedanceTask.h
- src/mc_tasks/ImpedanceTask.cpp
If the controller `dt` is less than the default `dt` (= 0.005), a patch of this PR is needed to set the cutoff period of low-pass filter correctly.
This is because
https://github.com/mmurooka/mc_rtc/blob/4e6364427f90841d34db56675d2fe28650a561d5/src/mc_tasks/ImpedanceTask.cpp#L178
is called before
https://github.com/mmurooka/mc_rtc/blob/4e6364427f90841d34db56675d2fe28650a561d5/src/mc_tasks/ImpedanceTask.cpp#L189
Since the low-pass filter requires `cutoffPeriod > 2 * dt`, the `cutoffPeriod` will be overwritten based on the `dt` before the update.
https://github.com/jrl-umi3218/mc_rtc/blob/a9a8dde1cf00f4e22a5a4090b5e333e77915e725/include/mc_filter/LowPass.h#L51-L55
> [mc_tasks] set cutoff period of low-pass filter again when dt is updated

- doc/_i18n/en/tutorials/usage/gui.md
- doc/_i18n/jp/tutorials/usage/gui.md
- include/mc_rtc/gui/StateBuilder.h
- include/mc_rtc/gui/StateBuilder.hpp
- src/mc_rtc/gui/StateBuilder.cpp
- tests/testGUIStateBuilder.cpp
This PR allows simpler cleanup when multiple elements are added to a category.
For example, for the root category, the following:
```cpp
gui()->addElement({}, Elem1, Elem2, Elem3);
gui()->removeElement({}, Elem1);
gui()->removeElement({}, Elem2);
gui()->removeElement({}, Elem3);
```
Can be replaced with:
```cpp
gui()->addElement(this, {}, Elem1, Elem2, Elem3);
gui()->removeElements({}, this);
```
By default, the `removeElements(category, source)` function is not recursive (i.e. it only removes elements at the provided category) as the goal is to "targeted" removals. However, this can be tweaked via a flag.
The PR also contains changes that ensures the GUI message is cleaned up when elements are removed (previously empty categories could persist forever)
This new capability is not used …
> Simplify GUI cleanup

- include/mc_solver/QPSolver.h
- src/mc_solver/QPSolver.cpp
This uses the observation pipeline but integrates the result over the real state of the robot. This might not be suitable for all robots depending on the dynamics of the system it is connected to.
This also introduces clearer synonyms for the two existing feedback mode.
> [mc_solver] Add a new FeedbackType

- src/mc_control/fsm/Controller.cpp
Currently, the initial pose of the robots is loaded slightly inconsitently:
- For the main robot is is loaded in `fsm::Controller::reset()`
- For additional robots it is loaded in `fsm::Controller::Controller()` constructor
In general this is not an issue, but this causes inconsitencies in `mc_mujoco` with only some robots loaded in the correct position. This PR loads `init_pos` for all robots in the constructor, which makes it more consistent and fixes the aforementioned issue.
> [fsm] Load init_pos consistently for MainRobot and other robots

- .github/workflows/build-others.yml
- .github/workflows/build.yml
- utils/build_and_install.sh
- utils/config_build_and_install.focal.sh
This PR contains small fixes to the `build_and_install` script:
- The existance check for the catkin workspaces is currently broken (it checks for `<src>/catkin_ws/src/devel/setup.bash` instead of `<src>/catkin_ws/devel/setup.bash`). This causes the catkin workspaces to build before the update/installation.
- On Ubuntu 20.04:
- When building with both python2 and python3 the pip2 boostrap script causes `pip3` to get uninstalled, even though the ubuntu package apears intact. This causes the python3 bindings generation to fail down the line. This is fixed by forcing a reinstallation of `python3-pip` after installing `pip2`.
- When forcing the install with `python3`, the suggested python paths at the end of the script are wrong (pointing to the non-existing python2 install).
I also added the …
> [build_and_install] Fixes about python3 and catkin workspaces

- include/mc_rbdyn/Robot.h
- src/mc_control/fsm/Controller.cpp
- src/mc_rbdyn/Robot.cpp
Changes introduced by #247 break controllers that rely on calling `Robot::loadRSDFFromDir` themselves.
This is because this function calls `fixSurfaces()`, that in the new implementation also attempts to create `Frames` for all surfaces in the controller. Since most of these frames already exist, this fails.
This PR fixes the behaviour by:
- Decoupling `fixSurfaces` from frames creation
- Only loading the surfaces that haven't already been loaded (and displaying a warning if the surfaces already exist)
- Independently creating the frames from the robot module in a new function `Robot::createModuleFrames()`
Additionally, I've added a mechanism to load additional frames from the FSM configuration, which is a common use case. For example:
```yaml
robots:
panda_femur:
init_pos:
translation: …
```
> Fix additional loading of surfaces from RSDF and load additional frames in the FSM configuration

- debian/libmc-rtc-dev.install
- include/mc_control/Contact.h
- include/mc_control/MCController.h
- include/mc_control/fsm/Controller.h
- include/mc_rtc/clock.h
- include/mc_solver/QPSolver.h
- src/CMakeLists.txt
- src/mc_control/MCController.cpp
- src/mc_control/fsm/Controller.cpp
- src/mc_solver/QPSolver.cpp
- src/mc_solver/QPSolver_setContacts.cpp
The main purpose of this PR is to bring in the helpers from the FSM controller into the regular controller class
This is essentially:
- renaming `mc_control::fsm::Contact` to `mc_control::Contact` (keeping an alias in the `fsm` namespace)
- moving code from the FSM controller to the regular controller
- Tightening the relationship between contacts in `mc_solver::QPSolver` and the contacts in the controller
- Improving the presentation of contacts in the GUI
> Improve controller base

- include/mc_rbdyn/Robots.h
- include/mc_solver/QPSolver.h
- src/mc_rbdyn/Robots.cpp
- tests/controllers/mc_rtc.conf.in
This PR adds an overload to `Robots::loadRobot(...)` allowing to load a robot from a robot module, but using a custom name.
Required by https://github.com/jrl-umi3218/mc_state_observation/pull/13
> [mc_rbdyn] Load robot from module with a custom name

- src/mc_observers/BodySensorObserver.cpp
- src/mc_rbdyn/Robot.cpp
When creating a robot module with no body sensor (e.g Panda), a default one is added. However, this sensor has neither a name nor a parent, which causes issues down the line, notably with observers assuming that sensors have a valid parent link.
Thus we:
- Ensure that all `BodySensors` have a valid parent
- Create a valid `BodySensor` (attached to the base link) in the case were none were provided by the robot module
> [BodySensor] Initialize default body sensor with a valid parent

- doc/_data/schemas/State/EnableController.json
- doc/_examples/json/State/EnableController.json
- doc/_examples/yaml/State/EnableController.yaml
- include/mc_control/fsm/states/EnableController.h
- src/mc_control/fsm/states/CMakeLists.txt
- src/mc_control/fsm/states/EnableController.cpp
- src/mc_control/mc_global_controller.cpp
This allows to perform programmatic switches between controllers:
- By calling `datastore().call("Global::EnableController", "NextControllerName")` from your code
- By using the `mc_control::fsm::EnableControllerState` in your FSM
@gergondet What are we missing to get this merged? Mohamed and Ahmed would like to use it to switch between their controllers (teleoperated grasping and tossing).
> [global] Expose EnableController in the datastore

- include/mc_control/MCController.h
This PR allows to get a non const pointer to the GUI from a const controller. This enables to modify the GUI without needing the right to modify the controller (for example in a state-observer).
> Make the getter for gui a const function in controller interface

- src/mc_control/mc_global_controller.cpp
This PR properly initializes the real robot attitude when using `InitAttitudeFromSensors: true`.
See #284 .
> [global] Initialize real robot from sensors

- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
I confirmed that this PR solves https://github.com/jrl-umi3218/mc_rtc/issues/177 for lipm_walking_controller with JVRC1 in choreonoid.
It represents the moment part of the equation (12) in [Stephane's paper](https://arxiv.org/pdf/1809.07073.pdf) around the robot CoM instead of the world origin. This seems to keep the numerical calculations stable by avoiding too large moment value when the robot moves away from the origin (but the QP should be equivalent, and I still don't know the exact reason why this is necessary).
I have confirmed that the robot can walk with lipm_walking_controller near and away from the origin, but be careful with merging as there may be unforeseen side effects.
For information, I've encountered the same behavior with my multi-contact motion stabilizer (i.e., the …
> [StabilizerTask] distribute moment around CoM instead of world origin

- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
The balancing issue in loco-manipoulation has been solved with this patch (https://gite.lirmm.fr/jrp-2019/mc_hwm_planner/-/issues/14#note_21892).
This change was suggested by @mitsuharu-morisawa to avoid using the feed back value as a reference. `anchorFrame(robot())` is modified by the `CoPTask`, which is unsuitable for use as a reference of the base link rotation.
This change has been used in HRP5P experiments for several months and in HRP2KAI experiments for several weeks.
I don't know if we can merge this change as it is, but I will make a Pull Request because it is a change that solves a major issue in balance control.
> [mc_tasks] set roll and pitch of target torso zero.

- include/mc_rbdyn/Robot.h
- include/mc_rbdyn/ZMP.h
- src/mc_rbdyn/Robot.cpp
- src/mc_rbdyn/ZMP.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
With the introduction of stacktraces into the `mc_rtc::log::error_and_throw` it becomes very expensive to throw and catch exceptions (much more so than regular exceptions). The default ZMP computations throw on errors so this PR introduces variants that do not throw to communicate issues.
This variant is used in the StabilizerTask
> Add non-throwing version of ZMP computations

- include/mc_filter/LowPassCompose.h
- include/mc_filter/utils/clamp.h
- include/mc_rbdyn/Gains.h
- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_rtc/Configuration.h
- include/mc_rtc/MessagePackBuilder.h
- include/mc_rtc/log/utils.h
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_rbdyn/Robot.cpp
- src/mc_robots/jvrc1.cpp
- src/mc_rtc/Configuration.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask_log_gui.cpp
- tests/LoggerTraits.cpp
- tests/testConfiguration.cpp
This PR is composed of two elements with regards to the LIPMStabilizer Task : 
- The derivation of the DCM feedback is now done using a complementary filtering of a low pass filter between the model base derivate of the DCM and its derivate based on the varitaion of the measured DCM 
- The DCM feedback gain can now be 2d with respect of the orientation of the yaw of the "BODY" frame. 
- This update yet creates some conflict with former version configuration of the Stabilizer due to the conversion of the gain in 2d and must be fixed before merging
> LIPMstabilizer : Correct the derivator gain and add dimensional gain on DCM feedback

- plugins/ROS/src/mc_rtc_ros/ros.cpp
This PR (along with https://github.com/rohanpsingh/mc_rtc_msgs/commit/ee76a5b882ceb0c346d0a23183a10e0c816f1cc6) will create a new ROS topic to publish `JointSensor` readings. I think it is useful to publish the `JointSensor` info over ROS (beside having them in the logs) to possibly trigger beeps/alarms or other safety mechanisms.
It's a draft currently because I'm unable to figure how to publish the topic name under `/mc_rtc` namespace, instead of `/real` and `/control` prefixes. 
Currently, I assume `mc_rtc_msgs/JointSensors` to have the following structure:
```
std_msgs/Header header
uint32 seq
time stamp
string frame_id
string[] name
float64[] motor_temperature
float64[] driver_temperature
float64[] motor_current
```
But a possible variation could be to have two structures, with …
> Publish JointSensors on ROS

- CMakeLists.txt
- doc/_i18n/en/tutorials/usage/gui.md
- doc/_i18n/jp/tutorials/usage/gui.md
- include/mc_control/ControllerClient.h
- include/mc_rtc/Configuration.h
- include/mc_rtc/MessagePackBuilder.h
- include/mc_rtc/gui.h
- include/mc_rtc/gui/Polyhedron.h
- include/mc_rtc/gui/elements.h
- include/mc_rtc/gui/types.h
- include/mc_rtc/utils/heatmap.h
- src/CMakeLists.txt
- src/mc_control/ControllerClient.cpp
- src/mc_rtc/Configuration.cpp
- src/mc_rtc/MessagePackBuilder.cpp
- src/mc_rtc/internals/json.h
- tests/dummyServer.cpp
- tests/testConfiguration.cpp
This PR adds an `mc_rtc::gui::Polyhedron` element, represented as a list of triangles (with points in clockwise order).
Additionally a list of per-vertex color can be provided (in which case rviz will display it by interpolating the colors in-between each triangle vertices. We can also choose to display edges as lines and vertices as 3D points (either using each vertex color, or providing a custom color for all edges). And of course transparent colors are supported so that we can see the robot behind ;)
Example:
```cpp
mc_rtc::gui::PolyhedronTriangles polyhedron_vertices_{
// Upper pyramid
{-1, -1, 0}, {1, -1, 0}, {0, 0, 1}, {1, -1, 0}, {1, 1, 0}, {0, 0, 1}, {1, 1, 0}, {-1, 1, 0}, {0, 0, 1}, {-1, 1, 0}, {-1, -1, 0}, {0, 0, 1},
// Lower pyramid
{-1, -1, 0}, {0, 0, -1}, {1, -1, 0}, {1, -1, …
```
> [GUI] Implement Polyhedron element

- include/mc_control/ControllerClient.h
- include/mc_rtc/Configuration.h
- include/mc_rtc/gui/StateBuilder.h
- include/mc_rtc/gui/StateBuilder.hpp
- include/mc_rtc/gui/plot/Abscissa.h
- include/mc_rtc/gui/plot/AbscissaOrdinate.h
- include/mc_rtc/gui/plot/Ordinate.h
- include/mc_rtc/gui/plot/Polygon.h
- include/mc_rtc/gui/plot/Polygons.h
- include/mc_rtc/gui/plot/types.h
- src/mc_control/ControllerClient.cpp
- src/mc_control/ControllerServer.cpp
- src/mc_rtc/gui/StateBuilder.cpp
- tests/dummyServer.cpp
This PR makes sure all data in a plot is displayed
This avoids misinterpretation when looking at online plots where discontinuities might not appear as bad online as they actually are (and can usually be seen offline)
> Ensure plots contain all the data

- plugins/ROS/src/mc_rtc_ros/ros.cpp
Currently `ROS` is initialized with:
```
ros::init(argc, argv, name.c_str(), ros::init_options::NoSigintHandler);
```
This means that interrupt signals (`Ctrl-C`) will not be caught by ROS itself, and thus that code execution will be interrupted immediately. In particular:
```cpp
while(ros::ok())
{
MCGlobalController gc;
}
// destructors will not be called upon Ctrl-C (controllers, plugins, observers, etc)
```
Since in that case destructors are not called, this can cause issues down the line.
I can't think of any reason why we should be disabling the default signal handler, and doing so is confusing.
> [ROS] Restore ROS Signal Handler

- include/mc_control/mc_global_controller.h
- include/mc_rbdyn/BodySensor.h
- plugins/ROS/src/mc_rtc_ros/ros.cpp
- src/mc_observers/KinematicInertialPoseObserver.cpp
This patch is required for robots whose BodySensor orientation is not identity relative to the parent link.
Fixes https://github.com/isri-aist/mc_rhps1/issues/10
> [bugfix] Treat the transformation between sensor and parent link in KinematicInertialPoseObserver

- doc/_data/schemas/common/PostureTask_targets_properties.json
- include/mc_tasks/PostureTask.h
- src/mc_tasks/PostureTask.cpp
- tests/controllers/plugins/TestCanonicalRobotController.cpp
>> As a proposal, in PostureTask, it would be useful to specify dimWeight by passing a pair of joint name and weight via mc_rtc::Configuration.
>
> Sounds good. Maybe a jointWeight entry? (note that jointGains/jointStiffness can do this at the stiffness/damping level of the task)
(from https://github.com/jrl-umi3218/mc_rtc/issues/314#issuecomment-1350492087)
I verified that the following configurations can be loaded correctly.
```yaml
jointWeights:
WAIST_R: 100
WAIST_P: 200
WAIST_Y: 300
```
Documentation and testing may need to be updated, but I'm not familiar with them, so I'd appreciate it if the maintainer could do that.
> [mc_tasks] Add PostureTask::jointWeights

- utils/mc_rtc_new_controller.in.py
- utils/mc_rtc_new_fsm_controller.in.py
Since `config_` is a member of `MCController`, it would be confusing to have the same member in an inherited class.
https://github.com/jrl-umi3218/mc_rtc/blob/8d2ad7e5db5153c99fd929c0869da0acc0cb2dbf/include/mc_control/MCController.h#L715-L716
> [utils/mc_rtc_new_controller] Remove config from the controller members

- include/mc_tasks/ImpedanceGains.h
The `wrench` member was probably uninitialized in the default gain of ImpedanceTask.
https://github.com/jrl-umi3218/mc_rtc/blob/47098df603d2d38b51b484ae7220ee8a4d1cca6d/include/mc_tasks/ImpedanceTask.h#L235
> [mc_tasks] Initialize wrench with zero in ImpedanceGains::Default

- .github/workflows/build.yml
- include/mc_rtc/log/Logger.h
- include/mc_rtc/log/utils.h
- src/mc_rtc/Logger.cpp
- src/mc_rtc/internals/LogEntry.h
- src/mc_rtc/iterate_binary_log.cpp
- utils/mc_bin_utils.in.cpp
This PR changes  the way the log information is stored in the log.
- Record the callback type only once
- Small reduction in output size
- Small reduction in logging workload at runtime
- Slightly higher complexity for parsing the output
- Pave the way to events' logging
- Run through the callbacks in the order they were called
- Required by the parser to reconstruct correctly
- Better cache locality (maybe?)
Overall, it improves the logging performance by about 25% on e.g. BaseLineWalkingController
Old logs are still compatible with all the tools in the framework.
> Introduce new log format to improve logging performances

- doc/_data/schemas/MetaTask/FirstOrderImpedanceTask.json
- doc/_examples/json/MetaTask/FirstOrderImpedanceTask.json
- doc/_examples/yaml/MetaTask/FirstOrderImpedanceTask.yaml
- include/mc_tasks/FirstOrderImpedanceTask.h
- src/CMakeLists.txt
- src/mc_tasks/FirstOrderImpedanceTask.cpp
- src/mc_tasks/ImpedanceTask.cpp
- tests/testSchemaExamples.in.cpp
This PR adds a `FirstOrderImpedanceTask` to provide contact force control of the stance foot and tracking control of the swing foot in the unified task. This task is used in both of [BaselineWalkingController](https://github.com/isri-aist/BaselineWalkingController) and [Motion6DoF](https://github.com/isri-aist/motion6dof) (This will soon become a more general multi-contact controller).
This task is similar to the existing `DampingTask` but has improvements in the parameter API (using `ImpedanceGains` class) and class structure (inheriting from `ImpedanceTask`). For a discussion of the class structure of the force tasks, please refer to the https://github.com/jrl-umi3218/mc_rtc/pull/100#issuecomment-739474086
Probably the following files also need to be added, but I am not familiar with …
> [mc_tasks] Add FirstOrderImpedanceTask

- doc/_i18n/en.yml
- doc/_i18n/en/tutorials/introduction/configuration.html
- doc/_i18n/jp.yml
- doc/_i18n/jp/tutorials/introduction/configuration.html
- include/mc_control/MCController.h
- include/mc_control/fsm/Controller.h
- include/mc_rtc/loader.h
- include/mc_rtc/loader.hpp
- src/mc_control/MCController.cpp
- src/mc_control/fsm/Controller.cpp
- src/mc_control/mc_global_controller.cpp
- src/mc_rtc/loader.in.cpp
- tests/controllers/CMakeLists.txt
- tests/controllers/TestRobotConfigurationController.cpp
- tests/controllers/TestRobotConfigurationController.in.yaml
- tests/controllers/TestRobotConfigurationController.jvrc1.in.yaml
- tests/controllers/TestRobotConfigurationController.jvrc2.in.yaml
See #325 for the motivation of this PR
This exposes a robot's specific configuration for given controllers that can be stored alongside the controller or in the user's home directory.
I have left out the other components that could benefit from this (e.g. observers and plugins) but this can be added based on the functionalities added here.
> [mc_control] Allow loading a robot specific configuration

- include/mc_control/MCController.h
- src/mc_control/MCController.cpp
Allow functionalities similar to those discussed in https://github.com/isri-aist/BaselineWalkingController/pull/12
The approach relies on installed files rather than nested keys in the configuration but can achieve the same effect, i.e., overwrite any main configuration entry from extraneous files
As noted in the doxygen, the extra configuration files are loaded after the robots' specific files for the robot that are provided at construction but after the ones loaded through the `robots` entry. Otherwise it would become really hard to track the loading order since those extra files can themselves specify extra robots to load.
> [mc_control] Add overwrite support for configuration

- binding/python/mc_control/c_mc_control.pxd
- binding/python/mc_control/mc_control.pyx
- include/mc_control/Contact.h
- include/mc_rtc/Configuration.h
- src/mc_control/MCController.cpp
- src/mc_control/samples/LIPMStabilizer/CMakeLists.txt
- src/mc_control/samples/LIPMStabilizer/etc/LIPMStabilizer.in.yaml
- tests/testConfiguration.cpp
- utils/mc_rtc_new_fsm_controller.in.py
The benefit of this is illustrated in the LIPMStabilizer sample which now enables solver contacts with any biped robot.
To support this, `mc_rtc::Configuration` now also supports `std::optional<T>` with the following caveat.
Conversion might have to be more explicit than usual, for example, given this yaml:
```yaml
double: 42.42
```
The following could be expected:
```cpp
// int i = config("double"); // <-- Throws because the types do no match
std::optional<int> o = config("double"); // <-- Should return std::nullopt
```
But it actually throws because `config("double")` can be converted to an `int` and is thus used by the assignment operator of `std::optional<int>` instead of the conversion from `Configuration` to `std::optional<int>`
To use the `std::optional` conversion in such a …
> [mc_control] Allow r1 and/or r2 to be omitted in contact yaml

- include/mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h
- include/mc_tasks/lipm_stabilizer/Contact.h
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask_log_gui.cpp
This PR adds a new method to distribute the force during a double support phase.
It uses a set of reference ZMP in a defined horizon.
The CoP are then modelled as a 1st order w.r.t the generated reference with parameters lambda and delay w.r.t the previous reference.
The distribution computes the reference CoP to send to the admittances tasks in order to obtain the desired ZMP.
This method does not rely on the classic DCM feedback scheme and is supposed to be used in a case where the centroidal dynamic is already computed.
The previous use of the lipm_stabilizer remains.
This has been tested using the ismpc controller with HRP-2KAI and HRP-4CR real robots.
It also added other accessor on the stabilizer state.
> New method for force distribution based on horizon reference

- include/mc_rtc/MessagePackBuilder.h
- include/mc_rtc/log/FlatLog.h
- include/mc_rtc/log/FlatLog.hpp
- include/mc_rtc/log/utils.h
- tests/testLogger.cpp
- tests/utils.h
These vector are still recorded and retrieved as dynamic sized vectors. However at log time there's no need to copy the data to a temporary dynamic vector.
> [mc_rtc/Logger] Allow to log fixed size vector without a copy

- .pre-commit-config.yaml
- src/mc_control/fsm/states/CMakeLists.txt
- src/mc_control/fsm/states/PythonState.cpp
- src/mc_control/python/CMakeLists.txt
- src/mc_control/python/python_controller.cpp
- src/mc_rtc/python.h
- tests/controllers/CMakeLists.txt
- tests/controllers/TestPythonState.cpp
- tests/controllers/TestPythonState.in.yaml
- tests/controllers/test_python/__init__.py
- tests/controllers/test_python/test_python_state.py
This PR:
- fixes an initialize/finalize issue with PythonState (and potentially PythonController) when they are used in a row (e.g. a Python state instance transiting to another Python state instance)
- adds a test for Python states
> Fix issue with using multiple PythonState instances in a row

- debian/libmc-rtc-dev.install
- debian/libmc-rtc.install
- doc/_i18n/en/tutorials/recipes/observers.md
- doc/_i18n/jp/tutorials/recipes/observers.md
- include/mc_observers/ObserverLoader.h
- include/mc_observers/ObserverPipeline.h
- include/mc_observers/api.h
- include/mc_rtc/loader.h
- include/mc_rtc/loader.hpp
- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/CMakeLists.txt
- src/mc_control/MCController.cpp
- src/mc_control/fsm/states/CMakeLists.txt
- src/mc_control/samples/EndEffector/mc_end_effector_controller.cpp
- src/mc_control/samples/Impedance/mc_impedance_controller.cpp
- src/mc_control/samples/Posture/mc_posture_controller.cpp
- src/mc_control/samples/Text/mc_text_controller.cpp
- src/mc_observers/ObserverPipeline.cpp
- src/mc_rtcMacros.in.cmake
- tests/controllers/CMakeLists.txt
- tests/controllers/TestObserverConfigurationController.cpp
- tests/controllers/TestObserverConfigurationController.in.yaml
- tests/controllers/observers/TestObserver.cpp
- tests/controllers/observers/TestObserver.jvrc1.yaml
- tests/controllers/observers/TestObserver.yaml
This PR adds:
- global observers' configuration files (in `${MC_OBSERVERS_RUNTIME_INSTALL_PREFIX}/etc/${ObserverType}.yaml` and `${HOME}/.config/mc_rtc/observers/${ObserverType}.yaml`
- robot (module) based configuration files (in `${MC_OBSERVERS_RUNTIME_INSTALL_PREFIX}/${ObserverType}/${robot}.yaml` and `${HOME}/.config/mc_rtc/observers/${ObserverType}/${robot}.yaml`)
This also add CMake macro helpers to install those files
ToDo:
> [mc_observers] Add observers' configuration

- include/mc_solver/CoMIncPlaneConstr.h
- include/mc_tvm/CoMInConvexFunction.h
- src/mc_solver/CoMIncPlaneConstr.cpp
- src/mc_solver/CollisionsConstraint.cpp
- src/mc_solver/utils/jointsToSelector.h
- src/mc_tvm/CoMInConvexFunction.cpp
- tests/controllers/TestCoMInBoxController.cpp
Follow up jrl-umi3218/Tasks#88
Note that (as done in the test) it is recommended to give it the same joints as the CoM task (if any) to avoid surprising interactions between the constraint and the task
> [mc_solver] Allow to select active joints in CoMIncPlaneConstr

- src/mc_rbdyn/RobotModule.cpp
- src/mc_robots/jvrc1.cpp
- src/mc_robots/jvrc1.h
- tests/testCanonicalRobot.cpp
Due to an erroneous stopping condition in the loop comparing robot devices between canonical and non-canonical robots, we had an infinite loop that would result in out-of-bound access of the devices arrays.
This PR fixes the bug and adds the corresponding unit test.
Will merge when CI passes.
Thanks @Dwaaap for debugging the issue :+1:
> [bugfix] Fix out-of-bound access when loading canonical robots

- binding/python/include/mc_control_fsm_wrapper.hpp
- binding/python/include/mc_rtc_wrapper.hpp
- doc/_data/schemas/ConstraintSet/CollisionsConstraint.json
- include/mc_solver/CollisionsConstraint.h
- include/mc_solver/ConstraintSet.h
- include/mc_solver/QPSolver.h
- src/mc_solver/CollisionsConstraint.cpp
- src/mc_solver/QPSolver.cpp
- src/mc_solver/TVMQPSolver.cpp
- src/mc_solver/TasksQPSolver.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
- src/mc_tasks/lipm_stabilizer/StabilizerTask_log_gui.cpp
- utils/mc_bin_utils.in.cpp
> Fix some warnings with StabilizerTask

- include/mc_control/mc_global_controller.h
- include/mc_rtc/log/Logger.h
- src/mc_control/mc_global_controller.cpp
This PR adds one feature:
- `log.addLogEntry` can use the `overwrite = true` parameter to force an entry into the log even if it already exists
It also contains a fix to plugin performance logging. This was particularly problematic when the controller includes enough plugin to trigger a resize on the `plugins_before_`/`plugins_after_` vectors since it would then access freed memory during logging.
> [mc_control] Correctly log plugin performances 

- binding/python/mc_control/c_mc_control.pxd
- binding/python/mc_control/mc_control.pxd
- binding/python/mc_control/mc_control.pyx
- include/mc_control/ControllerClient.h
This is just an introduction to a new feature I am experimenting with right now. I thought it was interesting and will submit a PR, but it may not necessarily need to be merged.
I thought it would be useful If we could send commands (walking, reaching, etc.) of mc_rtc controller from a Python script or interpreter, and I realized this by using Python bindings in [ControllerClient](https://github.com/jrl-umi3218/mc_rtc/blob/47177743b1df404c5a039ef159396a2ab93d0cd1/include/mc_control/ControllerClient.h#L51). This PR adds that bindings. 
This allows the Python interpreter to send walking and gripper opening/closing commands, as shown in the video below, using BaselineWalkingController as an example. (BaselineWalkingController does not require any changes for this purpose.) In addition to …
> Add Python bindings for ControllerClient

- src/mc_rbdyn/Robot.cpp
This PR modifies the `mc_rbdyn::Robot::forwardKinematics` such as the convexes attached to a robot are also updated. Otherwise, the convexes' location keeps their initial pose unless they are used in a constraint.
This allows `mc_rbdyn::Robot::convex` function to return an up-to-date convex.
> [mc_rbdyn::Robot] Update the convex

- include/mc_observers/KinematicInertialPoseObserver.h
- src/mc_observers/KinematicInertialPoseObserver.cpp
Replace custom implementation of `mergeRoll1Pitch1WithYaw2` with state-observation's implementation now that it is a dependency of `mc_rtc`.
I tested in simulation, will test with HRP4 this afternoon.
> [KinematicInertialObserver] Use state observation

- include/mc_observers/KinematicInertialPoseObserver.h
- src/mc_observers/KinematicInertialPoseObserver.cpp
This PR fixes the mistakes introduced by #388 (I have temporarely reverted it on master with [d4de8d3](https://github.com/jrl-umi3218/mc_rtc/commit/d4de8d312049420e965a68672cd0abef860df95a))
During walking I could see no differences checking the results of the old versus new method.
However, while perturbing the robot manually (dragging it around in choreonoid), there are still slight differences.
For example (displayed as RPY angles)
```
[info] New:   0.22885 -0.218569    2.3249
[info] Old:  0.234254 -0.212752   2.29964
[info] New:  0.231229 -0.220776   2.32437
[info] Old:  0.236799 -0.214775   2.29859
[info] New:  0.233628 -0.223039   2.32383
[info] Old:   0.23937 -0.216849   2.29751
[info] New:  0.236055 -0.225358   2.32327
[info] Old:  0.241975 -0.218971    2.2964
[info] New: …
```
> [KinematicInertial] Fix use of state-observation

- doc/_data/schemas/SpaceVecAlg/ForceVecd.json
- doc/_data/schemas/SpaceVecAlg/ImpedanceVecd.json
- doc/_data/schemas/SpaceVecAlg/MotionVecd.json
- doc/_i18n/en/tutorials/usage/mc_rtc_configuration.md
- doc/_i18n/jp/tutorials/usage/mc_rtc_configuration.md
- include/mc_rtc/Configuration.h
- include/mc_rtc/Default.h
- src/mc_rtc/Configuration.cpp
- tests/testConfiguration.cpp
- tests/testConfigurationHelpers.cpp
- tests/testJsonIO.cpp
This PR introduces changes to `mc_rtc::Configuration` that will be used in a subsequent PR that introduces a schema-like structure builder to mc_rtc. It is the first of three PRs leading to `mc_rtc::Schema` introduction
The following features have been added:
- Support for loading/saving `std::variant`
- Support for intrusive methods for user-defined load/save operations (in addition to the existing and non-intrusive approach)
- Add `Configuration::find(key)`, `Configuration(key, others...)` and `Configuration.find<T>(keys, others...)`
I started to refactor the use `Configuration::has` (e.g. replace the very common usage of `if(cfg.has("foo")) { foo = cfg("foo"); do_something(foo); }` with `if(auto foo = cfg.find("foo")) { do_something(foo); }` but many of these instances will be better …
> [mc_rtc/Configuration] Improvements for Schema introduction

- include/mc_control/ControllerClient.h
- include/mc_rtc/Configuration.h
- include/mc_rtc/MessagePackBuilder.h
- include/mc_rtc/gui/Form.h
- include/mc_rtc/gui/details/traits.h
- include/mc_rtc/gui/elements.h
- src/mc_control/ControllerClient.cpp
- tests/CMakeLists.txt
- tests/gui_AdvancedForm.cpp
- tests/gui_SampleClient.cpp
- tests/gui_SampleServer.cpp
- tests/gui_TestServer.h
Add multiple elements to form more complex forms in mc_rtc GUI.
This is the second of three PR introducing Schema-like structures in mc_rtc
This PR adds the following elements to form:
- `FormPoint3DInput`, `FormTransformInput` and `FormRotationInput` allow interactive 3D elements in a Form
- `FormObjectInput` allows to nest a form inside a form
- `FormGenericArrayInput` allows to create an array of arbitrary objects into a form
- `FormOneOfInput` lets you create a form that nest one of the specified form (the target is to support `variant` integration in a form)
These features are supported in a branch of mc_rtc-imgui and mc_rtc_ros and I will open PR once this gets merged
> [GUI] Add many form elements

- doc/_data/schemas/State/Meta.json
- include/mc_control/fsm/Executor.h
- src/mc_control/fsm/Executor.cpp
- src/mc_control/fsm/states/Meta.cpp
This PR allows to skip the reset of the posture tasks before transitioning to the next state. This has been requested multiple times, and proves useful in some cases where the user does not want to keep the current posture. Example:
```yaml
base: Meta
ResetPostures: false
transitions:
- [ChooseState, A, StateA, Auto]
- [ChooseState, B, StateB, Auto]
- [StateA, OK, HalfSitting, Auto]
- [StateB, OK, HalfSitting, Auto]
- [HalfSitting, OK, ChooseState, Auto]
```
This will set the desired posture to HalfSitting instead of keeping it to the current posture. Not that with `ResetPostures: true` in this example, the behaviour would be counterintuitive: the effet of the HalfSitting state is immediately canceled by the resetting of the posture tasks done by the Exectutor (as we are not awaiting for …
> [FSM/Executor] Make resetting posture tasks optional

- include/mc_control/mc_global_controller.h
- include/mc_rbdyn/JointSensor.h
- src/mc_control/MCController.cpp
- src/mc_control/mc_global_controller.cpp
- Can be used to act on servo off or motor alarm situations. 
- Set to `true` by default
> [JointSensor] include motor status property

- .github/workflows/build-others.yml
- .github/workflows/build.yml
- doc/_data/tutorials.yml
- doc/_i18n/en.yml
- doc/_i18n/en/tutorials/usage/schema.md
- doc/_i18n/jp.yml
- doc/_i18n/jp/tutorials/usage/schema.md
- doc/tutorials/usage/schema.md
- include/mc_rtc/Schema.h
- include/mc_rtc/SchemaMacros.h
- tests/CMakeLists.txt
- tests/gui_Schema.cpp
- tests/samples_Schema.h
- tests/testSchema.cpp
This PR adds support for defining Schema-like structures within mc_rtc.
The motivation and the implementation are documented in the doc joined to this PR.
I'm introducing it in this state to:
1. Allow us to start using it in some projects
2. Use it internally in mc_rtc
It is likely the feature will evolve a bit after merging as it gets more practical use.
> Add mc_rtc::Schema (BETA)

- include/mc_rbdyn/ForceSensor.h
- include/mc_rbdyn/ForceSensorCalibData.h
- include/mc_rtc/SchemaMacros.h
- include/mc_rtc/log/Logger.h
- include/mc_rtc/macros/pp_id.h
- include/mc_rtc/pragma.h
- plugins/Replay/src/Replay.cpp
- src/mc_control/Ticker.cpp
- src/mc_control/mc_global_controller.cpp
- src/mc_rbdyn/ForceSensor.cpp
- src/mc_rtc/Logger.cpp
- src/mc_rtc/internals/LogEntry.h
- tests/controllers/replay/CMakeLists.txt
- tests/controllers/replay/TestReplayController.cpp
- tests/controllers/replay/TestReplayController_Play.in.yaml
This PR introduces two changes to improve Replay accuracy and ease of use
1. Log the initial configuration
==
In some interfaces, in particular mc_openrtm, the initial configuration may be different from the initial values of the encoder. This can lead to some discrepancies in the replay. (usually small but in practice this hinders the search for failing conditions)
2. Log the force sensors' calibrations
==
This simplifies the usage of the Replay significantly as the Replay will now use the same force sensors' calibration parameters that were used during recording.
> Improve Replay accuracy

- include/mc_tasks/lipm_stabilizer/StabilizerTask.h
- src/mc_tasks/lipm_stabilizer/StabilizerTask.cpp
This PR properly disables the stabilizer when the robot is in the air by ensuring that all feedback gains are set to zero when lifting occurs and resets them to their pre-lifting values when the robot is back on the ground.
Please note however that in case of erroneous lift-off detection, this might have some side effects as the derivators and integrators are reset (current existing behaviour). However I don't think we ever had erroneous detection of whether the robot is in the air, so it's not a big concern.
> [StabilizerTask] Fix disabling when the robot is in the air

- doc/_i18n/en/tutorials/usage/schema.md
- doc/_i18n/jp/tutorials/usage/schema.md
- include/mc_rtc/Schema.h
- tests/samples_Schema.h
- tests/testSchema.cpp
Add support for `std::map` in `mc_rtc::Schema`.
> [Schema] Add support for std::map

- .pre-commit-config.yaml
- doc/_i18n/en.yml
- doc/_i18n/en/tutorials/introduction/configuration.html
- doc/_i18n/jp.yml
- doc/_i18n/jp/tutorials/introduction/configuration.html
- doc/_includes/mc_rtc_configuration_row.html
- include/mc_control/mc_global_controller.h
- include/mc_rbdyn/RobotLoader.h
- src/mc_control/MCController.cpp
- src/mc_control/Ticker.cpp
- src/mc_control/mc_global_controller.cpp
- src/mc_control/mc_global_controller_configuration.cpp
- src/mc_rbdyn/RobotLoader.cpp
- tests/CMakeLists.txt
- tests/global_controller_configuration/CMakeLists.txt
- tests/global_controller_configuration/mc_rtc.in.yaml
- tests/global_controller_configuration/testGlobalControllerConfiguration.in.cpp
This PR allows to rename the main robot declared in `mc_rtc.yaml` as the one named in a controller configuration in `robots`
> [MCControler] Update main robot name

- include/mc_tasks/ImpedanceTask.h
- include/mc_tasks/TransformTask.h
- src/mc_tasks/ImpedanceTask.cpp
- src/mc_tasks/TransformTask.cpp
We noticed with @Hugo-L3174 that it is possible to call `ImpedanceTask::targetSurface` but that the implementation is wrong. In the current implementation calling the parent's `TransformTask::refVelB` and `TransformTask::target` are explicitly disallowed as the impedance task needs to keep track of the desired target (that is modified through the impedance equation to provide a compliance pose/velocity/acceleration that is then given as the TransformTask's target). However since `ImpedanceTask::targetSurface` is not hidden it is possible to directly modify the target of the underlying `TransformTask` without modifying the impedance target.
To fix this I propose:
- To make `TransformTask::target` virtual, which allows `ImpedanceTask` to override it to keep track of the desired target pose …
> [ImpedanceTask] Fix use of targetSurface and implement targetFrame/targetFrameVelocity

- include/mc_control/ControllerClient.h
- include/mc_rtc/gui/RobotMsg.h
- include/mc_rtc/gui/elements.h
- include/mc_rtc/gui/types.h
- src/mc_control/ControllerClient.cpp
This PR aims to provide more information of the `mc_rbdyn::Robot` through the `mc_rtc::gui`.
To do so, the PR adds a `RobotMsg` type handling all the info to be transmitted.
This will allow in the future to add more information about the `mc_rbdyn::Robot` through the `mc_rtc::gui` without the need to patch all gui clients repo.
However this update implies that all gui client using the robot module must be patched to handle the `RobotMsg`
> [mc_rtc_gui] change the robot type to handle more informations of mc_rbdyn::Robot

- include/mc_rbdyn/Robot.h
- include/mc_rbdyn/RobotData.h
- include/mc_rbdyn/RobotFrame.h
- src/mc_rbdyn/Robot.cpp
- src/mc_rbdyn/RobotFrame.cpp
- tests/controllers/TestCanonicalRobotController.cpp
This function allows to insert a new force sensor into a robot at run-time.
This also updates the frames of every robot that uses the same data. This means that adding a force sensor to the control robot will not only update the frames of the control robot but also the real/observed robot and their outputs counterpart.
The sensor calibration file is not searched, the usual scenario where this might be used implies that calibration files do not exist or do not reside in the usual location so searching for them would be wasteful.
> [mc_rbdyn] Implement addForceSensor

- .github/workflows/build.yml
- plugins/ROS/src/mc_rtc_ros/ros.cpp
- utils/build_and_install.sh
This PR fix a segfault error when adding the new  `mc_rbyn:Robot::addForceSensor` and using the `mc_rtc_ros` plugin.
As the msg list was not updated after adding a new force sensor, the plugin throwed a segfault.
The PR will add new force sensors to the msg list.
> [mc_rtc_ros] Fix force sensor publishing

- plugins/CMakeLists.txt
- plugins/ROS/CMakeLists.txt
- src/mc_control/mc_global_controller_configuration.cpp
- src/mc_rtcMacros.in.cmake
This PR fixes three small issues with the plugin autoload feature:
- defaults autoload to `OFF`, one can pass the `AUTOLOAD` parameter to the `add_plugin` macro to restore the old behavior
- when the autoload option is switched off, the file is also uninstalled (previously it had to be removed manually)
- trim the content of the autoload file, this prevents an issue when the file is edited manually
> Autoload improvments

- plugins/ROS/src/mc_rtc_ros/ros.cpp
- src/mc_rtcMacros.in.cmake
Avoid signint handler message and error concerning FULL ROS MESSAGE QUEUE by removing siginthandler as it has been done for ros1. 
[https://docs.ros.org/en/iron/p/rclcpp/generated/function_namespacerclcpp_1a026b2ac505c383735117de5d1679ed80.html](https://docs.ros.org/en/iron/p/rclcpp/generated/function_namespacerclcpp_1a026b2ac505c383735117de5d1679ed80.html)
> Remove the default all signal handler to avoid  signal_handler message and FULL ROS MESSAGE QUEUE error

- .github/workflows/build-others.yml
- .github/workflows/build.yml
- .github/workflows/docker/Dockerfile.debian_bullseye
- .github/workflows/docker/build-docker.sh
- .gitignore
- tests/controllers/TestFSMStateOptions.cpp
This PR fixes and updates the CI:
- Fix sync with gitlab: Pierre's token expired
- Use `mc-rtc-superbuild` instead of the deprecated `build_and_install.sh`  script. This both simplifies the CI setup and ensures that we check if the same setup as the recommended one for developers. This is somewhat redundant with the CI of mc-rtc-superbuild itself. I however intend to upgrade `mc-rtc-superbuild` ci to perform more exhaustive checks, including all common extensions and interfaces, plus a few "standard demos". Thus `mc_rtc`'s CI will remain checks on mc_rtc itself and its minimal set of dependencies.
- Add build checks for ubuntu jammy
- For windows: mc-rtc-superbuild is not (yet) supported so we keep the old-school manual build setup around
- MacOS: disable for now as build fails since the …
> Upgrade CI

- include/mc_rtc/gui/RobotMsg.h
This PR fixes an issue with the vector conversion for the `mc_rtc::gui::RobotMsg`.
> [RobotMsg] fix wrong vector conversion for tau, alpha, and alphaD

- utils/mc_bin_to_log.cpp
- utils/mc_bin_to_log_main.cpp
This PR intends to avoid missing milliseconds information in the exported csv file given after running `mc_bin_to_log`. This happens when increasing dt. 
It can be problematic to differentiate data as they might have the same time value.
> mc_bin_to_log : set double precision 

- doc/_i18n/en/tutorials/usage/schema.md
- doc/_i18n/jp/tutorials/usage/schema.md
- include/mc_rtc/MessagePackBuilder.h
- include/mc_rtc/Schema.h
- src/mc_rtc/MessagePackBuilder.cpp
- tests/samples_Schema.h
This PR adds support for loading and saving `Eigen::MatrixXd` objects with an `mc_rtc::Schema`
> Schema: Add support for Eigen::MatrixXd
