doc/_includes/tutorials/introduction/com-controller/controller.cpp, doc/tutorials/introduction/com-controller.html, doc/tutorials/introduction/multi-robot-controller.html
I tried MyFirstController tutorials and found some typos and a missing line.
=> [doc] add a missing line and fix typos

.github/workflows/build.yml, .github/workflows/package.yml, CHANGELOG.md, doc/_data/schemas/MetaTask/MomentumTask.json, doc/_examples/json/MetaTask/MomentumTask.json, doc/_examples/yaml/MetaTask/MomentumTask.yaml, include/mc_tasks/MomentumTask.h, src/CMakeLists.txt, src/mc_tasks/MomentumTask.cpp
This PR adds a wrapper for `tasks::qp::MomentumTask`
=> mc_tasks::MomentumTask

plugins/ROS/src/mc_rtc_ros/ros.cpp
This PR ensures that TFs are published when surfaces are dynamically added to a robot
=> [ROS] Ensure surfaces TF are always up-to-date

include/mc_control/ControllerClient.h, include/mc_rtc/MessagePackBuilder.h, include/mc_rtc/gui.h, include/mc_rtc/gui/Table.h, include/mc_rtc/gui/elements.h, src/mc_control/ControllerClient.cpp, tests/dummyServer.cpp
This PR adds support for creating tables in the GUI
=> [GUI] Add Table element

doc/_data/interfaces.yml
This PR includes slight changes to the mc_naoqi interface description in documentation and updates the URL to the interface project.
=> [doc] Update mc_naoqi interface info

doc/_data/schemas/common/State.json
This PR fixes typos in doc/_data/schemas/common/State.json.
=> [doc] fix typos

doc/_includes/tutorials/introduction/running/cnoid.html, doc/_includes/tutorials/introduction/running/feedback.html, doc/_includes/tutorials/introduction/running/vrep.html, doc/tutorials/recipes/fsm-example.md, doc/tutorials/recipes/fsm-main-states.md
This PR adds small fixes to the files in doc directory.
=> add small fixes for files in doc directory

doc/_data/carousel.yml
This PR adds a new video to the main mc_rtc website page.
The video demonstrates two Human-Robot Interaction experiments powered by mc_rtc.
The video also explains mc_naoqi communication interface and all associated projects in detail.
=> [doc] Add new video to the main website page

utils/build_and_install.sh
Sorry the lines were in the wrong order
=> [build_and_install] Correct the displayed text at the end of the installation

.github/workflows/build-others.yml, .github/workflows/build.yml, .github/workflows/docker/Dockerfile, include/mc_rtc/Configuration.h, include/mc_rtc/MessagePackBuilder.h, src/mc_rtc/Configuration.cpp, src/mc_rtc/MessagePackBuilder.cpp, src/mc_rtc/internals/json.h, utils/build_and_install.sh, utils/config_build_and_install.macos.sh
Also:
- improve performance on `sva::ForceVecd` and `sva::MotionVecd` serialization (logging and GUI)
- Attempting to fix macOS CI*
*Debian Buster and Ubuntu Focal report a failed build but looking into the log it seems that the build is OK up until the end where some disk space issue come up
=> [mc_rtc] Add support for sva::ImpedanceVecd serialization

include/mc_tasks/PostureTask.h, src/mc_tasks/PostureTask.cpp
This is a follow-up on https://github.com/jrl-umi3218/Tasks/pull/75
=> [mc_tasks] Add support for refVel/refAccel in PostureTask

utils/build_and_install.sh
Switch from https://gite.lirmm.fr/mc-hrp2/hrp2_drc to https://gite.lirmm.fr/mc-hrp2/hrp2_drc_description
Related to https://github.com/isri-aist/hrp2kai/pull/9 and https://gite.lirmm.fr/mc-hrp2/mc-hrp2/-/merge_requests/3
=> Update hrp2_drc_description URL to use automatically generated package

utils/build_and_install.sh
Otherwise the script fails at git clone phase
=> [utils] Specify "main" as the default branch in hrp2_drc_description

doc/_data/schemas/mc_rbdyn/RobotModule.json, include/mc_rbdyn/Robot.h, include/mc_rbdyn/RobotModule.h, src/mc_rbdyn/Robot.cpp, src/mc_rbdyn/configuration_io.cpp, src/mc_solver/KinematicsConstraint.cpp, tests/testJsonIO.cpp
Superseeds !221 on GitLab
Opened on GitHub for CI
=> introduce joint jerk bounds

include/mc_control/ControllerClient.h, include/mc_rtc/gui/Form.h, src/mc_control/ControllerClient.cpp
Treat https://github.com/jrl-umi3218/mc_rtc/issues/119#issuecomment-884950809
close https://github.com/jrl-umi3218/mc_rtc/issues/119
=> [GUI] allow to set default value for FormComboInput

src/mc_rtc/logging.cpp
Fixes compilation on Windows with more recent spdlog versions
=> Adapt to spdlog >= 1.8.3

src/mc_control/python/python_controller.cpp
=> [python] Unset the Python interrupt handler if needed

.github/workflows/build.yml, .github/workflows/package.yml, src/mc_solver/QPSolver.cpp
Fixes https://github.com/jrl-umi3218/mc_rtc_ros/issues/27
=> [QPSolver] Ensure that lambdaVec size is updated when setting contact

src/mc_rtc/internals/yaml.h, tests/testConfiguration.cpp
- Add logic around bool conversion to ignore y/n
- Handle simple merge keys
Merge keys exist in YAML 1.1 but were removed in YAML 1.2. They are not supported by yaml-cpp which we use internally for all YAML handlings (note that internally all YAML inputs are converted to JSON). However, they can be very useful for us (as demonstrated in the unit test):
```yaml
default-col: &default-col
iDist: 0.05
sDist: 0.01
damping: 0
collisions:
- b1: body1
b2: body2
<<: *default-col
- b1: bodyN
b2: bodyM
<<: *default-col
sDist: 0.04 # overwrite some of the default values
```
However, YAML 1.1 also allows the following:
```yaml
first: &first
a: 0
b: 1
second: &second
a: 1
c: 0
third:
<<: [*first, *second]
```
This is not supported here as it would be more complicated and the semantic is not very clear.
=> [mc_rtc] YAML improvement

binding/python/mc_rbdyn/c_mc_rbdyn.pxd, binding/python/mc_rbdyn/mc_rbdyn.pyx
As requested in https://github.com/jrl-umi3218/SpaceVecAlg/issues/42 (cc. @mmurooka )
=> [bindings] Add bindings for rpy_utils

CHANGELOG.md, include/mc_rbdyn/Collision.h, src/mc_rbdyn/configuration_io.cpp, src/mc_solver/CollisionsConstraint.cpp, tests/controllers/CMakeLists.txt, tests/controllers/TestCollisionController.cpp
See https://github.com/jrl-umi3218/Tasks/pull/82
=> [mc_solver] Add joint selection for the collision constraint

src/mc_tasks/AdmittanceTask.cpp
Closes #261
@mehdi-benallegue can you confirm I understood your point correctly? Thanks!
=> [mc_tasks::AdmittanceTask] Avoid filtering of feedforward velocity

src/mc_control/mc_global_controller.cpp
This fixes an issue introduced by #245 and now the robots are always correctly position according to the configuration if present
=> Skip attitude initialization when configured in the controller

doc/_data/robots.yml, utils/build_and_install.sh
- Similar changes may be needed for HRP4 (although I don't know which ones we should use)
- The same changes should be made for the new installation system, mc-rtc-superbuild.
=> Update URL of HRP2 and HRP5P

include/mc_rtc/logging.h, src/mc_rtc/logging.cpp, tests/test_interpolation.cpp, tests/tests_config.h.in
=> Disable notifications in tests

.github/workflows/build.yml, include/mc_control/fsm/Executor.h
=> [mc_control] Executor should not be moved or copied

src/mc_control/ControllerClient.cpp, tests/dummyServer.cpp
This fixes the two issues raised in #334 as they both originate from wrong decoding in the ControllerClient class
=> [GUI] Fix issues with handling of Polyhedron in ControllerClient

src/mc_rbdyn/Robot.cpp
=> [mc_rbdyn] Fix collision objects after fixing collision transforms

src/mc_control/generic_gripper.cpp
=> [mc_control] Compute alphaOut for the grippers

plugins/Replay/src/Replay.cpp, plugins/Replay/src/Replay.h
This is especially useful when the replay plugin is used outside of mc_rtc_ticker
=> [Replay] Add GUI control for iterations

doc/_i18n/en/tutorials/usage/live-plotting.md, doc/_i18n/jp/tutorials/usage/live-plotting.md, include/mc_rtc/gui/details/traits.h, include/mc_rtc/gui/plot/AbscissaOrdinate.h, tests/dummyServer.cpp
This enables use case where the data is obtained asynchronously and we need to push new data when it arrives
=> [mc_rtc/gui/plot] Allow to provide XY data as chunks

src/mc_tasks/ImpedanceTask.cpp
See https://github.com/jrl-umi3218/mc_rtc/pull/428#issuecomment-2068871527
=> [ImpedanceTask] Log compliance pose
